//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM_WindowsForms.HM_WCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HM_WCFService.IHMService")]
    public interface IHMService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/ValidaConexionSQL", ReplyAction="http://tempuri.org/IHMService/ValidaConexionSQLResponse")]
        bool ValidaConexionSQL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/ValidaConexionSQL", ReplyAction="http://tempuri.org/IHMService/ValidaConexionSQLResponse")]
        System.Threading.Tasks.Task<bool> ValidaConexionSQLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/CreateCustomer", ReplyAction="http://tempuri.org/IHMService/CreateCustomerResponse")]
        string CreateCustomer(string CustomerName, string Contact, string Email, string Rif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/CreateCustomer", ReplyAction="http://tempuri.org/IHMService/CreateCustomerResponse")]
        System.Threading.Tasks.Task<string> CreateCustomerAsync(string CustomerName, string Contact, string Email, string Rif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/ListarCustomer", ReplyAction="http://tempuri.org/IHMService/ListarCustomerResponse")]
        HM_Entities.Customer[] ListarCustomer(string Rif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/ListarCustomer", ReplyAction="http://tempuri.org/IHMService/ListarCustomerResponse")]
        System.Threading.Tasks.Task<HM_Entities.Customer[]> ListarCustomerAsync(string Rif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/DeleteCustomer", ReplyAction="http://tempuri.org/IHMService/DeleteCustomerResponse")]
        string DeleteCustomer(string Rif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/DeleteCustomer", ReplyAction="http://tempuri.org/IHMService/DeleteCustomerResponse")]
        System.Threading.Tasks.Task<string> DeleteCustomerAsync(string Rif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/ValidarCustomerByRif", ReplyAction="http://tempuri.org/IHMService/ValidarCustomerByRifResponse")]
        HM_Entities.Customer ValidarCustomerByRif(string Rif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/ValidarCustomerByRif", ReplyAction="http://tempuri.org/IHMService/ValidarCustomerByRifResponse")]
        System.Threading.Tasks.Task<HM_Entities.Customer> ValidarCustomerByRifAsync(string Rif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/CreateItem", ReplyAction="http://tempuri.org/IHMService/CreateItemResponse")]
        string CreateItem(string Codigo, string Description, decimal Price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/CreateItem", ReplyAction="http://tempuri.org/IHMService/CreateItemResponse")]
        System.Threading.Tasks.Task<string> CreateItemAsync(string Codigo, string Description, decimal Price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/ListarItem", ReplyAction="http://tempuri.org/IHMService/ListarItemResponse")]
        HM_Entities.Item[] ListarItem(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/ListarItem", ReplyAction="http://tempuri.org/IHMService/ListarItemResponse")]
        System.Threading.Tasks.Task<HM_Entities.Item[]> ListarItemAsync(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/DeleteItem", ReplyAction="http://tempuri.org/IHMService/DeleteItemResponse")]
        string DeleteItem(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/DeleteItem", ReplyAction="http://tempuri.org/IHMService/DeleteItemResponse")]
        System.Threading.Tasks.Task<string> DeleteItemAsync(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/ValidarItemByCod", ReplyAction="http://tempuri.org/IHMService/ValidarItemByCodResponse")]
        HM_Entities.Item ValidarItemByCod(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/ValidarItemByCod", ReplyAction="http://tempuri.org/IHMService/ValidarItemByCodResponse")]
        System.Threading.Tasks.Task<HM_Entities.Item> ValidarItemByCodAsync(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/CreateSale", ReplyAction="http://tempuri.org/IHMService/CreateSaleResponse")]
        string CreateSale(HM_Entities.Sales objVentas, HM_Entities.SalesDetail[] ListaItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/CreateSale", ReplyAction="http://tempuri.org/IHMService/CreateSaleResponse")]
        System.Threading.Tasks.Task<string> CreateSaleAsync(HM_Entities.Sales objVentas, HM_Entities.SalesDetail[] ListaItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/ListarSales", ReplyAction="http://tempuri.org/IHMService/ListarSalesResponse")]
        HM_Entities.Sales[] ListarSales(int SaleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/ListarSales", ReplyAction="http://tempuri.org/IHMService/ListarSalesResponse")]
        System.Threading.Tasks.Task<HM_Entities.Sales[]> ListarSalesAsync(int SaleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/SumarLista", ReplyAction="http://tempuri.org/IHMService/SumarListaResponse")]
        int SumarLista(HM_Entities.Numeros[] N);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMService/SumarLista", ReplyAction="http://tempuri.org/IHMService/SumarListaResponse")]
        System.Threading.Tasks.Task<int> SumarListaAsync(HM_Entities.Numeros[] N);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHMServiceChannel : HM_WindowsForms.HM_WCFService.IHMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HMServiceClient : System.ServiceModel.ClientBase<HM_WindowsForms.HM_WCFService.IHMService>, HM_WindowsForms.HM_WCFService.IHMService {
        
        public HMServiceClient() {
        }
        
        public HMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidaConexionSQL() {
            return base.Channel.ValidaConexionSQL();
        }
        
        public System.Threading.Tasks.Task<bool> ValidaConexionSQLAsync() {
            return base.Channel.ValidaConexionSQLAsync();
        }
        
        public string CreateCustomer(string CustomerName, string Contact, string Email, string Rif) {
            return base.Channel.CreateCustomer(CustomerName, Contact, Email, Rif);
        }
        
        public System.Threading.Tasks.Task<string> CreateCustomerAsync(string CustomerName, string Contact, string Email, string Rif) {
            return base.Channel.CreateCustomerAsync(CustomerName, Contact, Email, Rif);
        }
        
        public HM_Entities.Customer[] ListarCustomer(string Rif) {
            return base.Channel.ListarCustomer(Rif);
        }
        
        public System.Threading.Tasks.Task<HM_Entities.Customer[]> ListarCustomerAsync(string Rif) {
            return base.Channel.ListarCustomerAsync(Rif);
        }
        
        public string DeleteCustomer(string Rif) {
            return base.Channel.DeleteCustomer(Rif);
        }
        
        public System.Threading.Tasks.Task<string> DeleteCustomerAsync(string Rif) {
            return base.Channel.DeleteCustomerAsync(Rif);
        }
        
        public HM_Entities.Customer ValidarCustomerByRif(string Rif) {
            return base.Channel.ValidarCustomerByRif(Rif);
        }
        
        public System.Threading.Tasks.Task<HM_Entities.Customer> ValidarCustomerByRifAsync(string Rif) {
            return base.Channel.ValidarCustomerByRifAsync(Rif);
        }
        
        public string CreateItem(string Codigo, string Description, decimal Price) {
            return base.Channel.CreateItem(Codigo, Description, Price);
        }
        
        public System.Threading.Tasks.Task<string> CreateItemAsync(string Codigo, string Description, decimal Price) {
            return base.Channel.CreateItemAsync(Codigo, Description, Price);
        }
        
        public HM_Entities.Item[] ListarItem(string Codigo) {
            return base.Channel.ListarItem(Codigo);
        }
        
        public System.Threading.Tasks.Task<HM_Entities.Item[]> ListarItemAsync(string Codigo) {
            return base.Channel.ListarItemAsync(Codigo);
        }
        
        public string DeleteItem(string Codigo) {
            return base.Channel.DeleteItem(Codigo);
        }
        
        public System.Threading.Tasks.Task<string> DeleteItemAsync(string Codigo) {
            return base.Channel.DeleteItemAsync(Codigo);
        }
        
        public HM_Entities.Item ValidarItemByCod(string Codigo) {
            return base.Channel.ValidarItemByCod(Codigo);
        }
        
        public System.Threading.Tasks.Task<HM_Entities.Item> ValidarItemByCodAsync(string Codigo) {
            return base.Channel.ValidarItemByCodAsync(Codigo);
        }
        
        public string CreateSale(HM_Entities.Sales objVentas, HM_Entities.SalesDetail[] ListaItem) {
            return base.Channel.CreateSale(objVentas, ListaItem);
        }
        
        public System.Threading.Tasks.Task<string> CreateSaleAsync(HM_Entities.Sales objVentas, HM_Entities.SalesDetail[] ListaItem) {
            return base.Channel.CreateSaleAsync(objVentas, ListaItem);
        }
        
        public HM_Entities.Sales[] ListarSales(int SaleId) {
            return base.Channel.ListarSales(SaleId);
        }
        
        public System.Threading.Tasks.Task<HM_Entities.Sales[]> ListarSalesAsync(int SaleId) {
            return base.Channel.ListarSalesAsync(SaleId);
        }
        
        public int SumarLista(HM_Entities.Numeros[] N) {
            return base.Channel.SumarLista(N);
        }
        
        public System.Threading.Tasks.Task<int> SumarListaAsync(HM_Entities.Numeros[] N) {
            return base.Channel.SumarListaAsync(N);
        }
    }
}
